[workspace]
channels = ["https://prefix.dev/conda-forge"]
platforms = ["win-64", "linux-64", "osx-arm64", "osx-64"]
preview = ["pixi-build"]

[workspace.build-variants]
boost = ["1.76.0", "1.75.0"]

[package]
authors = ["Wolf Vollprecht <wolf@prefix.dev>"]
description = "Showcases how to create a simple C++ executable with Pixi"
name = "boost-check"
version = "0.1.0"

[package.build]
backend = { name = "pixi-build-cmake", version = "*" }
channels = [
  "https://prefix.dev/pixi-build-backends",
  "https://prefix.dev/conda-forge",
]

[tasks.start]
cmd = "boost-checker"

[host-dependencies]
boost = "*"

[dependencies]
boost-check = { path = "." }
